##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Makefile lib
##

all:
	make -C ./my/
	make -C ./printf/
	make -C ./tools/

clean:
	make clean -C ./my/
	make clean -C ./printf/
	make clean -C ./tools/

fclean:
	make fclean -C ./my/
	make fclean -C ./printf/
	make fclean -C ./tools/

re : fclean all
